### PR TITLE
Major Refactor: Implement Redux

### PR DESCRIPTION
**Pull request by bryantee**
According to the **Three Principles of Redux** my entire app state should be the [single source of truth](https://github.com/reactjs/redux/blob/master/docs/introduction/ThreePrinciples.md#single-source-of-truth), and therefore everything state-wise should be in the single object tree within the single store.

Because of that I'm embarking on a major refactor of my app logic. Instead of passing down functions in the form of props to children, all to update state.... I will be doing `store.dispatch(action)`'s. This is going to require me to not only add Redux, actions, reducers, etc for all of this logic I already wrote, but also to re-think how my app is structured.

I'll be starting with Actions, and here's my thoughts so far:

### Redux Actions
Action | description
------ | -----------
COMPLETE_POMO | Update store to let know pomo session complete
GET_ARTICLES | Retrieves NYTimes articles using API
GET_ACTIVITY_STATS | Retrieve pomodoro activity stats
ADD_ACTIVITY | Adds an activity to track in the list
REMOVE_ACTIVITY | Remove an activity from the list
SELECT_AVTIVITY | Selects a current activity for the pomo session
START_POMO | Start / resume a pomo timer
PAUSE_POMO | Pause a pomo timer
SET_POMO_SECONDS | Sets pomo total time in seconds

----
### ToDo's
- [x] Fix tests to pass with Redux store

### CODE REVIEW

**Comment by bryantee** [comment]
Ok....needing to write a lot more actions than I was expecting.... :punch:

**Comment by rockchalkwushock** [comment]
Are you just writing actions or writing an action and then building at the corresponding reducer? You might not needs as many as you think if you handle the action/reducer as a promise. Especially if any of your acitonTypes seem to be boolean or share logic with another actionType. Below is how I set up my actions and reducers when using `redux` & `redux-promise-middleware` .

_actions.js_
```javascript
export default () => {
  const promise = new Promise((resolve, reject) => {
    // your code here
  });
  return {
    type: START_POMO,
    payload: promise
  };
};
```
_reducers.js_
```javascript
const initialState = {
    err: null,
    isFetched: false,
    // any other state you want to set.
};

export default(state = initialState, action) => {
  const { payload, type } = action;
    switch (type) {
        case `${START_POMO}_PENDING`:
            return {};
        case `${START_POMO}_FULFILLED`:
            return {
                ...state,
                isFetched: true,
               // items to concat to previous state object.
            };
        case `${START_POMO}_REJECTED`:
            return {
                ...state,
                isFetched: true,
                err: payload
            };
        default:
            return state;
    }
};
```

**Comment by bryantee** [comment]
@rockchalkwushock 

I started off stubbing out all the actions I thought I'd need and then went through 1-by-1 building them out and finish the reducer for each action, repeat.
 
I like this promise solution. Mario was showing me redux-pack. Are using the middleware for all actions or is it just for async actions like fetching data?

**Comment by rockchalkwushock** [comment]
I'm using `redux-pack` right now in my backend. I showed him that tech. Pretty cool stuff. You kind of have to think about things a little differently but it is very cool. Most everything I'm doing is utilizing `axios` to make calls to either Cloudinary or my API server. Feel free to look at my code anytime if you want to use `redux-pack`. I'm going build a simple to-do-list app after this using redux-pack and live code it. Pushing up to master tonight on the backend.

**Pull request merged**
