### PR TITLE
MVP Pomo Circle Progress Setup

### PR DESCRIPTION
**Pull request by bryantee**
Looking for any comments on these:
1. ~~Better organize components into stateful containers and dummy components (but how deal with setting state from child components?)~~  Found this [awesome article](http://lorenstewart.me/2016/10/31/react-js-forms-controlled-components/)
2. ~~Are properties `isRunning` and `isPaused` redundant? I thought it might be useful to distinguish between when a user has actively paused a pomo and when the current state is just `!isRunning` because it has either finished or not started. Thoughts?~~

screenshot from 2017-01-06 17-43-22

### CODE REVIEW

**Comment by rockchalkwushock** [comment]
You are always welcome to look at my [React Capstone](https://github.com/rockchalkwushock/Helios-Weather-App) for file structure and component ideas, although it's old compared to how I do things now. File structure is really dependent on the scale of your application and how many features you have.

## Possible file structure for managing features

```plaintext
src/
 commons/
  index.js
  - any files that will be common across many components.
 helpers/
  index.js
  - any helper functions
 modules/
  index.js - exports all items in modules
  entry/
    index.js - exports all items in entry
    App.jsx
    AppContainer.jsx
  feature1/
    sub-feature-1/
      Component.jsx - make as stupid as possible!
      Contatiner.jsx - connects to the Redux store.
    index.js - exports everything in feature1/
    actions.js - all actions that pertain to this feature.
    reducers.js - all reducers that pertain to this feature.
    types.js - all types that pertain to this feature.
  layout/
   index.js - exports all items in layout
   Navbar.jsx
   HomePage.jsx
   Page404.jsx - use for all routes not specified by router.
 redux/
  reducers/
    index.js - combine all reducers here
  store.js
 index.js - entry point for client 
 Routes.jsx - all routes here
package.json
README.md
yarn.lock
```

## Managing state & child components

You want your children to be **stupid**...well maybe not real life!
- Use stateless components for your children as much as possible.
- Use Container components to _connect_ your component to the store.
- Containers should be _connected_ to the store **NOT** components.

### Example

_LoginContainer.jsx_
```javascript
import { connect } from 'react-redux'; // connect to the store.
import Login from './Login'; // child component.
import { loginUser } from '../actions'; // action you want child component to have access to.

export default connect(
  null, // no state management so pass null in place of mapStateToProps
  { loginUser } // action
)(Login); // component being connected.

```

_Login.jsx_
```javascript
import React, { PropTypes } from 'react';
import { Field, reduxForm } from 'redux-form';
import { Button, Form, Grid, Message } from 'semantic-ui-react';
import { InputField } from '../../../commons';
import { loginValidation } from './validate';

const styles = {
  root: {
    position: 'relative'
  },
};

// notice the action comes in as a prop from the parent.
// ignore the other props, they pertain to Redux From.
const Login = ({ handleSubmit, loginUser, valid }) => (
  <div style={styles.root}>
    <Grid centered columns={3} style={{ height: '90vh' }} verticalAlign="middle">
      <Grid.Row>
        <Grid.Column>
          <Message
            attached
            header="Welcome to Admin!"
            content="Please login."
          />
          <Form className="attached fluid segment" onSubmit={handleSubmit(loginUser)}>
            <Form.Field>
              <label htmlFor='email'>Email</label>
              <Field
                icon="mail"
                component={InputField}
                placeholder="putinHeartsdonald@yandex.ru"
                name="email"
                type="email"
              />
            </Form.Field>
            <Form.Field>
              <label htmlFor='password'>Password</label>
              <Field
                icon="lock"
                component={InputField}
                placeholder="secretKGBpasswordHERE"
                name="password"
                type="password"
              />
            </Form.Field>
            <Button disabled={!valid} primary type="submit">Login</Button>
          </Form>
        </Grid.Column>
      </Grid.Row>
    </Grid>
  </div>
);

Login.propTypes = {
  handleSubmit: PropTypes.func.isRequired,
  loginUser: PropTypes.func.isRequired,
  valid: PropTypes.bool.isRequired
};

export default reduxForm({
  form: 'login',
  validate: loginValidation
})(Login);
```

Hope these nuggets of knowledge help you out! Feel free to ask questions as you work through your capstone...and what they hell is a _pomodoro web app_???

**Comment by benjaminj6** [comment]
I definitely think that consolidating `isRunning` and `isPaused` into a single property would be more DRY.

The way I see it, every time that `isPaused === false`, `isRunning === true`, and vice versa. Since they deal with the same aspect of the state, it would make sense to have a single property regarding the status of the timer.

**Comment by rockchalkwushock** [comment]
Good call @benjaminj6 totally missed commenting on that. If my reducer is working with an API I normally use a prop like `isFetched` or for the most part `isLoading`. In either case just using it as a boolean is a great way to handle loading state case or error cases in which the API call fails. The fail is much prettier with a loading graphic than a broken page.

**Comment by bryantee** [comment]
@rockchalkwushock

Thanks for helping out, as always. A few observations and questions:
- I notice that you pretty much always have a container analog for dummy children (or rather visa versa). I like this idea. Is that a common pattern you use?
- I also noticed in your components that you're passing an [object literal in instead of props](https://github.com/rockchalkwushock/Helios-Weather-App/blob/master/src/components/SearchBar.js#L3). I understand it's doing the same thing (I think), but is there a reason for this or just personal pref?

Oh, and a [Pomodoro](https://en.wikipedia.org/wiki/Pomodoro_Technique) is a technique for staying focused on a task. It's like a method for breaking a project or work into a series of chunks based on a set timeframe. So this app is basically a glorified timer with some additional functionality :alarm_clock: :hankey:

**Comment by rockchalkwushock** [comment]
@bryantee 

Yes for the most part you will see a _Container_ for handling the logic and then the child components that fall under it having props passed to them. I just prefer deconstructing so I can say `xyz` rather than `props.xyz`.

App sounds cool...might need to use it myself!

If you are using `redux` why not just use an actionCreator to cause a dispatch. The action will be dispatched to all reducers and the specific reducer using that actionType will fire updating the state. No need for managing state in the component itself. Set up an _initialState_ in your reducer and that will be the state for that start of the application (or the start of that portion of the application, you can have different _initialStates_ across your reducers):

```javascript
const initialState = {
 complete: false,
 error: false, // great way to determine if an error has occurred. You can then use message to display the error case.
 message: null, // if you want to display a message.
 isRunning: false
}
```

**Comment by bryantee** [comment]
@rockchalkwushock 

I'm definitely going to be using Redux for managing some overall app state, as I will have several other parts to the app that will need to communicate with each other. But I was thinking this container will be able to manage its own state and only dispatch crucial information to the store. Like when pomo is complete. What do you think?

**Comment by benjaminj6** [comment]
@bryantee 

Yeah I think you could eliminate the `isPaused` property and the `startPomo` could look something like this:

```js
    let intervalId = setInterval( () => {
      if (this.state.isRunning === false) { // should also be able to do `!this.state.isRunning`
        clearInterval(intervalId);
        return;
      }
      // check if pomo is complete, return if it is
      ...
      ...
      // set the state for percentage during each loop through
      ...
      ...
    }, 1000);
```

And then the `pausePomo` method could look like this

```js
pausePomo() {
  this.setState({ isRunning: false })
}
```

**Comment by rockchalkwushock** [comment]
@bryantee 

I just alway manage the whole state in Redux. 
One source of state.
One stop for logic checking. 
Ultimately one place to look for errors (using cases you can catch the errors to better know what you are up against).

Also FYI, if you are using `react-router-redux` to bind your _state_ & _route changes_ so they are keeping up with each other having state changes outside of the Redux store's knowledge would be no bueno. The routing changes will not be aware of it and your timer would reset to whatever the predefined state is in the component on a route change (I imagine you'll set that in `componentWillMount()` if you chose to go that route).

**Pull request merged**
